DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS auth;

CREATE TABLE auth (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100),
  hash TEXT
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY REFERENCES auth(id),
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  address VARCHAR (200),
  apt_no INT,
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100),
  zip_code INT,
  phone_no VARCHAR(100)
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name TEXT,
  type TEXT,
  store_quantity INT,
  description TEXT,
  img TEXT,
  price FLOAT
);

CREATE TABLE cart (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  product_id INT REFERENCES products(id),
  quantity INT
);

insert into products (id, name, type, store_quantity, description, img, price) values (1, 'Cottonmouth', 'notebook', 18, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'https://picsum.photos/500', '5.08');
insert into products (id, name, type, store_quantity, description, img, price) values (2, 'Tortoise, galapagos', 'notebook', 51, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'https://picsum.photos/500', '0.63');
insert into products (id, name, type, store_quantity, description, img, price) values (3, 'Sloth, two-toed', 'notebook', 20, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'https://picsum.photos/500', '7.19');
insert into products (id, name, type, store_quantity, description, img, price) values (4, 'Ground monitor (unidentified)', 'postcard', 28, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'https://picsum.photos/500', '2.27');
insert into products (id, name, type, store_quantity, description, img, price) values (5, 'Woodpecker, red-headed', 'notebook', 32, 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'https://picsum.photos/500', '6.13');
insert into products (id, name, type, store_quantity, description, img, price) values (6, 'Chestnut weaver', 'washi tape', 82, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'https://picsum.photos/500', '9.49');
insert into products (id, name, type, store_quantity, description, img, price) values (7, 'Tiger', 'washi tape', 45, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'https://picsum.photos/500', '1.57');
insert into products (id, name, type, store_quantity, description, img, price) values (8, 'Red brocket', 'postcard', 63, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'https://picsum.photos/500', '9.21');
insert into products (id, name, type, store_quantity, description, img, price) values (9, 'Goldeneye, common', 'notebook', 98, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'https://picsum.photos/500');
insert into products (id, name, type, store_quantity, description, img, price) values (10, 'Fox, grey', 'sticker', 79, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'https://picsum.photos/500', '8.20');
insert into products (id, name, type, store_quantity, description, img, price) values (11, 'Lizard, mexican beaded', 'sticker', 90, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'https://picsum.photos/500', '3.70');
insert into products (id, name, type, store_quantity, description, img, price) values (12, 'Partridge, coqui', 'postcard', 87, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'https://picsum.photos/500', '4.22');
insert into products (id, name, type, store_quantity, description, img, price) values (13, 'Eagle owl (unidentified)', 'notebook', 44, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'https://picsum.photos/500', '7.12');
insert into products (id, name, type, store_quantity, description, img, price) values (14, 'Squirrel, eurasian red', 'postcard', 26, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 'https://picsum.photos/500', '3.30');
insert into products (id, name, type, store_quantity, description, img, price) values (15, 'Madagascar fruit bat', 'sticker', 56, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'https://picsum.photos/500', '2.04');
insert into products (id, name, type, store_quantity, description, img, price) values (16, 'Mongoose, yellow', 'washi tape', 16, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'https://picsum.photos/500', '4.18');
insert into products (id, name, type, store_quantity, description, img, price) values (17, 'Bear, black', 'notebook', 80, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'https://picsum.photos/500', '3.15');
insert into products (id, name, type, store_quantity, description, img, price) values (18, 'American badger', 'washi tape', 57, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'hhttps://picsum.photos/500', '4.66');
insert into products (id, name, type, store_quantity, description, img, price) values (19, 'Ring-tailed lemur', 'notebook', 15, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'https://picsum.photos/500', '0.53');
insert into products (id, name, type, store_quantity, description, img, price) values (20, 'Wallaroo, common', 'notebook', 17, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'https://picsum.photos/500', '4.36');
insert into products (id, name, type, store_quantity, description, img, price) values (21, 'Common zebra', 'washi tape', 84, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'https://picsum.photos/500', '5.28');
insert into products (id, name, type, store_quantity, description, img, price) values (22, 'White-bellied sea eagle', 'notebook', 3, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'https://picsum.photos/500', '2.36');
insert into products (id, name, type, store_quantity, description, img, price) values (23, 'Western patch-nosed snake', 'sticker', 51, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'https://picsum.photos/500', '7.47');
insert into products (id, name, type, store_quantity, description, img, price) values (24, 'Waterbuck, defassa', 'sticker', 26, 'Cras pellentesque volutpat dui.', 'https://picsum.photos/500', '6.83');
insert into products (id, name, type, store_quantity, description, img, price) values (25, 'Grey heron', 'notebook', 72, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'https://picsum.photos/500', '1.07');
insert into products (id, name, type, store_quantity, description, img, price) values (26, 'Blue-footed booby', 'sticker', 21, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'https://picsum.photos/500', '0.53');
insert into products (id, name, type, store_quantity, description, img, price) values (27, 'Great skua', 'postcard', 18, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'https://picsum.photos/500', '7.25');
insert into products (id, name, type, store_quantity, description, img, price) values (28, 'Otter, cape clawless', 'sticker', 67, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://picsum.photos/500', '3.07');
insert into products (id, name, type, store_quantity, description, img, price) values (29, 'Black kite', 'notebook', 46, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'https://picsum.photos/500', '1.76');
insert into products (id, name, type, store_quantity, description, img, price) values (30, 'Lemur, sportive', 'postcard', 83, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'https://picsum.photos/500', '3.97');
insert into products (id, name, type, store_quantity, description, img, price) values (31, 'Dog, raccoon', 'sticker', 16, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'http://dummyimage.com/142x161.png/dddddd/000000', '8.54');
insert into products (id, name, type, store_quantity, description, img, price) values (32, 'Mountain goat', 'washi tape', 22, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 'https://picsum.photos/500', '8.34');
insert into products (id, name, type, store_quantity, description, img, price) values (33, 'Shrike, southern white-crowned', 'washi tape', 8, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'https://picsum.photos/500', '4.11');
insert into products (id, name, type, store_quantity, description, img, price) values (34, 'Mongoose, banded', 'notebook', 68, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'https://picsum.photos/500', '3.01');
insert into products (id, name, type, store_quantity, description, img, price) values (35, 'Fox, bat-eared', 'notebook', 24, 'Suspendisse ornare consequat lectus.', 'https://picsum.photos/500', '4.91');
insert into products (id, name, type, store_quantity, description, img, price) values (36, 'Grizzly bear', 'postcard', 11, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://picsum.photos/500', '3.53');
insert into products (id, name, type, store_quantity, description, img, price) values (37, 'Common goldeneye', 'washi tape', 69, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'https://picsum.photos/500', '7.55');
insert into products (id, name, type, store_quantity, description, img, price) values (38, 'Whale, long-finned pilot', 'notebook', 85, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'https://picsum.photos/500', '5.64');
insert into products (id, name, type, store_quantity, description, img, price) values (39, 'Pelican, australian', 'sticker', 96, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'https://picsum.photos/500', '1.58');
insert into products (id, name, type, store_quantity, description, img, price) values (40, 'Sage hen', 'postcard', 27, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'https://picsum.photos/500', '3.88');
insert into products (id, name, type, store_quantity, description, img, price) values (41, 'African black crake', 'notebook', 36, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'https://picsum.photos/500', '7.18');
insert into products (id, name, type, store_quantity, description, img, price) values (42, 'Raven, white-necked', 'postcard', 16, 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'https://picsum.photos/500', '6.55');
insert into products (id, name, type, store_quantity, description, img, price) values (43, 'Neotropic cormorant', 'notebook', 78, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'https://picsum.photos/500', '3.97');
insert into products (id, name, type, store_quantity, description, img, price) values (44, 'Galapagos mockingbird', 'sticker', 16, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'https://picsum.photos/500', '5.01');
insert into products (id, name, type, store_quantity, description, img, price) values (45, 'Eagle, golden', 'washi tape', 80, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'https://picsum.photos/500', '0.17');
insert into products (id, name, type, store_quantity, description, img, price) values (46, 'Slender loris', 'notebook', 12, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'https://picsum.photos/500', '8.71');
insert into products (id, name, type, store_quantity, description, img, price) values (47, 'Puma', 'postcard', 23, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'https://picsum.photos/500', '8.91');
insert into products (id, name, type, store_quantity, description, img, price) values (48, 'Indian star tortoise', 'washi tape', 29, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'https://picsum.photos/500', '7.49');
insert into products (id, name, type, store_quantity, description, img, price) values (49, 'Gull, lava', 'washi tape', 89, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'https://picsum.photos/500', '0.62');
insert into products (id, name, type, store_quantity, description, img, price) values (50, 'Bee-eater, carmine', 'postcard', 99, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'https://picsum.photos/500', '5.95');