DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS auth;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  address VARCHAR (200),
  apt_no VARCHAR (200),
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100),
  zip_code INT,
  phone_no VARCHAR(100)
);

CREATE TABLE auth (
  id INT REFERENCES users(id),
  email VARCHAR(100),
  hash TEXT
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  name TEXT,
  type TEXT,
  store_quantity INT,
  description TEXT,
  img TEXT,
  price FLOAT
);

CREATE TABLE cart (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id),
  product_id INT REFERENCES products(id),
  quantity INT
);

insert into products (name, type, store_quantity, description, img, price) values ('Tomatoes - Heirloom', 'postcard', 40, 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'https://picsum.photos/500', 3.79);
insert into products (name, type, store_quantity, description, img, price) values ('Lid Coffeecup 12oz D9542b', 'postcard', 17, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'https://picsum.photos/500', 14.22);
insert into products (name, type, store_quantity, description, img, price) values ('Ice Cream Bar - Oreo Cone', 'journal', 34, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'https://picsum.photos/500', 3.37);
insert into products (name, type, store_quantity, description, img, price) values ('Pork - Tenderloin, Fresh', 'journal', 13, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'https://picsum.photos/500', 3.61);
insert into products (name, type, store_quantity, description, img, price) values ('Mahi Mahi', 'journal', 100, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'https://picsum.photos/500', 12.25);
insert into products (name, type, store_quantity, description, img, price) values ('Sauce - Bernaise, Mix', 'journal', 6, 'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'https://picsum.photos/500', 6.2);
insert into products (name, type, store_quantity, description, img, price) values ('Cheese - Cream Cheese', 'postcard', 98, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'https://picsum.photos/500', 11.43);
insert into products (name, type, store_quantity, description, img, price) values ('Bok Choy - Baby', 'sticker', 9, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'https://picsum.photos/500', 4.43);
insert into products (name, type, store_quantity, description, img, price) values ('Soup - Campbells, Lentil', 'sticker', 11, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'https://picsum.photos/500', 12.56);
insert into products (name, type, store_quantity, description, img, price) values ('Oneshot Automatic Soap System', 'journal', 76, 'Morbi quis tortor id nulla ultrices aliquet.', 'https://picsum.photos/500', 3.62);
insert into products (name, type, store_quantity, description, img, price) values ('Puree - Raspberry', 'postcard', 56, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'https://picsum.photos/500', 11.01);
insert into products (name, type, store_quantity, description, img, price) values ('Cheese - Swiss Sliced', 'journal', 52, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'https://picsum.photos/500', 9.59);
insert into products (name, type, store_quantity, description, img, price) values ('Kellogs Cereal In A Cup', 'postcard', 60, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'https://picsum.photos/500', 12.8);
insert into products (name, type, store_quantity, description, img, price) values ('Yeast Dry - Fleischman', 'postcard', 62, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'https://picsum.photos/500', 4.55);
insert into products (name, type, store_quantity, description, img, price) values ('Kellogs Cereal In A Cup', 'sticker', 95, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 'https://picsum.photos/500', 7.87);
insert into products (name, type, store_quantity, description, img, price) values ('Soup - French Onion', 'journal', 51, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'https://picsum.photos/500', 9.77);
insert into products (name, type, store_quantity, description, img, price) values ('Bar Mix - Pina Colada, 355 Ml', 'postcard', 4, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'https://picsum.photos/500', 13.61);
insert into products (name, type, store_quantity, description, img, price) values ('Mikes Hard Lemonade', 'sticker', 38, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'https://picsum.photos/500', 1.84);
insert into products (name, type, store_quantity, description, img, price) values ('Bar Mix - Pina Colada, 355 Ml', 'sticker', 94, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'https://picsum.photos/500', 11.84);
insert into products (name, type, store_quantity, description, img, price) values ('Rosemary - Fresh', 'postcard', 35, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'https://picsum.photos/500', 6.3);
insert into products (name, type, store_quantity, description, img, price) values ('Mop Head - Cotton, 24 Oz', 'journal', 94, 'Nullam varius.', 'https://picsum.photos/500', 12.55);
insert into products (name, type, store_quantity, description, img, price) values ('Snapple Lemon Tea', 'sticker', 72, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'https://picsum.photos/500', 9.81);
insert into products (name, type, store_quantity, description, img, price) values ('Vermouth - White, Cinzano', 'sticker', 77, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'https://picsum.photos/500', 12.18);
insert into products (name, type, store_quantity, description, img, price) values ('Ham - Black Forest', 'journal', 4, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://picsum.photos/500', 11.96);
insert into products (name, type, store_quantity, description, img, price) values ('Yoplait - Strawbrasp Peac', 'postcard', 1, 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'https://picsum.photos/500', 10.28);
insert into products (name, type, store_quantity, description, img, price) values ('Wine - Merlot Vina Carmen', 'journal', 50, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'https://picsum.photos/500', 14.58);
insert into products (name, type, store_quantity, description, img, price) values ('Cookies - Amaretto', 'journal', 5, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'https://picsum.photos/500', 1.64);
insert into products (name, type, store_quantity, description, img, price) values ('Mayonnaise - Individual Pkg', 'postcard', 9, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'https://picsum.photos/500', 12.95);
insert into products (name, type, store_quantity, description, img, price) values ('Snapple - Mango Maddness', 'journal', 21, 'Integer ac neque. Duis bibendum.', 'https://picsum.photos/500', 11.25);
insert into products (name, type, store_quantity, description, img, price) values ('Gin - Gilbeys London, Dry', 'sticker', 76, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'https://picsum.photos/500', 11.43);
insert into products (name, type, store_quantity, description, img, price) values ('Towel Multifold', 'sticker', 37, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'https://picsum.photos/500', 2.77);
insert into products (name, type, store_quantity, description, img, price) values ('Cheese - Woolwich Goat, Log', 'sticker', 15, 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'https://picsum.photos/500', 11.29);
insert into products (name, type, store_quantity, description, img, price) values ('Liqueur - Melon', 'journal', 89, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'https://picsum.photos/500', 11.62);
insert into products (name, type, store_quantity, description, img, price) values ('Quinoa', 'journal', 10, 'Donec ut dolor.', 'https://picsum.photos/500', 14.96);
insert into products (name, type, store_quantity, description, img, price) values ('Sauce - Sesame Thai Dressing', 'journal', 18, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'https://picsum.photos/500', 2.78);
insert into products (name, type, store_quantity, description, img, price) values ('Lemonade - Black Cherry, 591 Ml', 'postcard', 18, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'https://picsum.photos/500', 6.42);
insert into products (name, type, store_quantity, description, img, price) values ('Potatoes - Yukon Gold, 80 Ct', 'postcard', 13, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'https://picsum.photos/500', 12.1);
insert into products (name, type, store_quantity, description, img, price) values ('Cake Sheet Combo Party Pack', 'journal', 12, 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'https://picsum.photos/500', 14.29);
insert into products (name, type, store_quantity, description, img, price) values ('Soup - Campbells, Minestrone', 'postcard', 4, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'https://picsum.photos/500', 2.54);
insert into products (name, type, store_quantity, description, img, price) values ('Beer - Moosehead', 'sticker', 41, 'Cras pellentesque volutpat dui.', 'https://picsum.photos/500', 13.94);
insert into products (name, type, store_quantity, description, img, price) values ('Food Colouring - Pink', 'journal', 89, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'https://picsum.photos/500', 4.55);
insert into products (name, type, store_quantity, description, img, price) values ('Cheese - Perron Cheddar', 'postcard', 82, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 'https://picsum.photos/500', 10.36);
insert into products (name, type, store_quantity, description, img, price) values ('Coffee - Dark Roast', 'postcard', 23, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'https://picsum.photos/500', 1.91);
insert into products (name, type, store_quantity, description, img, price) values ('Ginger - Ground', 'journal', 83, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'https://picsum.photos/500', 4.68);
insert into products (name, type, store_quantity, description, img, price) values ('Wine - Red, Pinot Noir, Chateau', 'journal', 100, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'https://picsum.photos/500', 14.68);
insert into products (name, type, store_quantity, description, img, price) values ('Nougat - Paste / Cream', 'postcard', 7, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'https://picsum.photos/500', 14.02);
insert into products (name, type, store_quantity, description, img, price) values ('Pomello', 'postcard', 94, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'https://picsum.photos/500', 6.42);
insert into products (name, type, store_quantity, description, img, price) values ('Raisin - Golden', 'postcard', 58, 'Morbi porttitor lorem id ligula.', 'https://picsum.photos/500', 9.96);
insert into products (name, type, store_quantity, description, img, price) values ('Bread - Pumpernickle, Rounds', 'postcard', 81, 'In quis justo. Maecenas rhoncus aliquam lacus.', 'https://picsum.photos/500', 12.91);
insert into products (name, type, store_quantity, description, img, price) values ('Honey - Lavender', 'sticker', 98, 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'https://picsum.photos/500', 6.94);
